//
//  SJCommonCodeLocalizedStringKeys.h
//  Pods
//
//  Created by admin on 2019/11/27.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN 

///
/// 本地化
///
typedef NSString * SJCommonCodeLocalizedStringKey;

UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyLongPressSpeedupPlayback;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyNoNetwork;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyWiFiNetWork;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyCellularNetwork;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyReplay;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyRetry;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyReload; 
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyLiveBroadcast;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyCancel;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDone;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUnstableNetworkPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyCellularNetworkPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyNoNetworkPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyPlaybackFailedPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyRecordsPreparingPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyRecordsToFinishRecordingPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyExportsExportingPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyExportsExportFailedPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyExportsExportSuccessfullyPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUploadsUploadingPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUploadsUploadFailedPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUploadsUploadSuccessfullyPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyScreenshotSuccessfullyPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyAlbumAuthDeniedPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyAlbumSavedToAlbumPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyOperationFailedPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDefinitionSwitchingPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt;
UIKIT_EXTERN SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDefinitionSwitchFailedPrompt;
NS_ASSUME_NONNULL_END
