//
//  SJCommonCodeLocalizedStringKeys.m
//  Pods
//
//  Created by admin on 2019/11/27.
//

#import "SJCommonCodeLocalizedStringKeys.h"

NS_ASSUME_NONNULL_BEGIN 

#if 0
(UIKIT_EXTERN\s)(SJCommonCodeLocalizedStringKey\sconst\s)([^;]+)
$2$3 = @"$3"
#endif

SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyLongPressSpeedupPlayback = @"SJCommonCodeLocalizedStringKeyLongPressSpeedupPlayback";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyNoNetwork = @"SJCommonCodeLocalizedStringKeyNoNetwork";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyWiFiNetWork = @"SJCommonCodeLocalizedStringKeyWiFiNetWork";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyCellularNetwork = @"SJCommonCodeLocalizedStringKeyCellularNetwork";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyReplay = @"SJCommonCodeLocalizedStringKeyReplay";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyRetry = @"SJCommonCodeLocalizedStringKeyRetry";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyReload = @"SJCommonCodeLocalizedStringKeyReload"; 
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyLiveBroadcast = @"SJCommonCodeLocalizedStringKeyLiveBroadcast";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyCancel = @"SJCommonCodeLocalizedStringKeyCancel";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDone = @"SJCommonCodeLocalizedStringKeyDone";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUnstableNetworkPrompt = @"SJCommonCodeLocalizedStringKeyUnstableNetworkPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyCellularNetworkPrompt = @"SJCommonCodeLocalizedStringKeyCellularNetworkPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyNoNetworkPrompt = @"SJCommonCodeLocalizedStringKeyNoNetworkPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyPlaybackFailedPrompt = @"SJCommonCodeLocalizedStringKeyPlaybackFailedPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyRecordsPreparingPrompt = @"SJCommonCodeLocalizedStringKeyRecordsPreparingPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyRecordsToFinishRecordingPrompt = @"SJCommonCodeLocalizedStringKeyRecordsToFinishRecordingPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyExportsExportingPrompt = @"SJCommonCodeLocalizedStringKeyExportsExportingPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyExportsExportFailedPrompt = @"SJCommonCodeLocalizedStringKeyExportsExportFailedPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyExportsExportSuccessfullyPrompt = @"SJCommonCodeLocalizedStringKeyExportsExportSuccessfullyPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUploadsUploadingPrompt = @"SJCommonCodeLocalizedStringKeyUploadsUploadingPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUploadsUploadFailedPrompt = @"SJCommonCodeLocalizedStringKeyUploadsUploadFailedPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyUploadsUploadSuccessfullyPrompt = @"SJCommonCodeLocalizedStringKeyUploadsUploadSuccessfullyPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyScreenshotSuccessfullyPrompt = @"SJCommonCodeLocalizedStringKeyScreenshotSuccessfullyPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyAlbumAuthDeniedPrompt = @"SJCommonCodeLocalizedStringKeyAlbumAuthDeniedPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt = @"SJCommonCodeLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyAlbumSavedToAlbumPrompt = @"SJCommonCodeLocalizedStringKeyAlbumSavedToAlbumPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyOperationFailedPrompt = @"SJCommonCodeLocalizedStringKeyOperationFailedPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDefinitionSwitchingPrompt = @"SJCommonCodeLocalizedStringKeyDefinitionSwitchingPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt = @"SJCommonCodeLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt";
SJCommonCodeLocalizedStringKey const SJCommonCodeLocalizedStringKeyDefinitionSwitchFailedPrompt = @"SJCommonCodeLocalizedStringKeyDefinitionSwitchFailedPrompt";
NS_ASSUME_NONNULL_END
